# -*- coding: utf-8 -*-
"""use_modal_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYCi0QhlNHj3n4--j4WZEemGOb5bsjq0
"""

### 10.11.2025 14:00

import numpy as np

import pickle

!ls

!wget https://github.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/raw/refs/heads/main/classifier.pickle

!ls

!wget https://github.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/raw/refs/heads/main/sc.pickle

!ls

# 12.11.2025

classifier_colab = pickle.load(open('classifier.pickle', 'rb'))

#!pip install scikit-learn --upgrade

# !pip install numpy --upgrade

scaler_colab = pickle.load(open('sc.pickle', 'rb'))

new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40, 20000]])))

new_pred

new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40, 20000]])))[:, 1]

new_pred_proba

new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42, 50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42, 50000]])))[:, 1]

new_pred_proba_2

